### ISSUE TITLE
Character should be in idle pose and have a basic animation idle loop playing

### ISSUE THREAD

**Issue by lalalune** [AtlasFoundation/AvatarCreator#2]
Currently character is in T pose. Should be in an idle pose and animated. We can get free poses from ActorCore, hopefully we don't need a whole retargeting thing.

This can be very complicated. If we have animation matching the character (which is rigged using Reallusion skeleton) then this is not so hard, but if we don't we need a retargeting solution.

I think that the best approach is to integrate Ossos and use the retargeting example provided here:
https://github.com/sketchpunklabs/ossos/blob/main/examples/threejs/003_retarget_and_springs.html

We might need to make a new retargeting profile for Character Creator character, since it is different than Mixamo rig which is generally standard.

![image](https://user-images.githubusercontent.com/18633264/170870463-b2ae461d-aa39-4071-91a5-bd331dc3112c.png)

**Comment by DavinciDreams** [comment]
> We might need to make a new retargeting profile for Character Creator character, since it is different than Mixamo rig which is generally standard.
> 
What about [ossos mixamoIKAnimatorRig.js](https://github.com/sketchpunklabs/ossos/blob/main/examples/_demo/lib/MixamoIKAnimatorRig.js)

**Comment by lalalune** [comment]
yeah that'd be a sweet option

**Comment by hardmode1337** [comment]
Do you guys lurk on discord ? would love to talk about Animation retargeting and working on a solution myself for my engine, have already had a chat with the guy behind OSSOS and he's shared some valuable information.

**Comment by DavinciDreams** [comment]
> Do you guys lurk on discord ? would love to talk about Animation retargeting and working on a solution myself for my engine, have already had a chat with the guy behind OSSOS and he's shared some valuable information.
> 
> We will all benefit form working together on the solutions.

We do!
