### ISSUE TITLE
Split heads with morph targets / blendshapes and remove from body to reduce model size in VRMs

### ISSUE THREAD

**Issue by lalalune** [AtlasFoundation/AvatarCreator#25]
Current the vrm base body assets are 48 megabytes. They can be much, much smaller with a bit of optimization.

-- Make sure that they are a single combined material
-- The head needs to be a separate mesh, and the blendshapes need to be removed from the body, this will reduce file size by 60%

**Comment by fire** [comment]
See https://github.com/AtlasFoundation/OpenCharacterCreator/issues/35#issuecomment-1145622690
