### ISSUE TITLE
Combine all VRM assets into single skeleton

### ISSUE THREAD

**Issue by lalalune** [AtlasFoundation/AvatarCreator#36]
Right now the export contains multiple skeletons. We really want all of our assets in the final export to be assigned to a single skeleton, and for the final file to only have one skeleton. This will hugely reduce file size.

**Comment by fire** [comment]
Don't try too hard on this.

If you add the meshes on the same skeleton, the various viewer gltf vrm viewers will merge.

See also https://github.com/godotengine/godot-tests/tree/master/tests/gltf_skeleton_tests/gltf_tests for weird cases.

**Comment by saddamjit** [comment]
Task Due Date is 18  June 2022
