### ISSUE TITLE
Atlas final textures together

### ISSUE THREAD

**Issue by lalalune** [AtlasFoundation/AvatarCreator#37]
https://github.com/oguzeroglu/TextureMerger

We will need to think about things like--

- Making sure all of our textures fit on one atlas and there is no wasted space
- Making sure more important parts get more space, or is UV proportionate
- Transparency objects are separated into a separate material

End ideal would be a single material and texture set (diffuse, normals, other PBR if contains)

**Comment by fire** [comment]
This is a dirty and not artist friendly but it'll work.

https://github.com/godot-extended-libraries/scene_merge/blob/master/merge.cpp

1. get position of the texel on each triangle
2. cut out the triangle
3. Place on a new url
4. Arrange direction of the cut out sheets
5. Use xatlas to optimize the triangle sheets
6. Export

**Comment by saddamjit** [comment]
Task Due Date is 22 June 2022
