### ISSUE TITLE
Can attempt to port to wasm

### ISSUE THREAD

**Issue by fire** [AtlasFoundation/AvatarCreator#39]
Can try to port to wasm if wanted.

**Comment by fire** [comment]
1. https://github.com/NectarJS/nectarjs
2. Check the list of missing features.

**Comment by lalalune** [comment]
Wow Nectar is insane.

I think it really comes down to if we can port three.js generally, right?

I think it might be effort overkill until we get into features like sculpting/touchup or baking stuff.
