### ISSUE TITLE
Skin Tone Swatch Selection

### ISSUE THREAD

**Issue by lalalune** [AtlasFoundation/AvatarCreator#44]
Right now we have a light <-> dark slider

Doesn't look great

As @fire suggested, a palette of nice skin tones would probably be better (ReadyPlayerMe does this)

**Comment by lalalune** [comment]
![image](https://user-images.githubusercontent.com/18633264/173467149-bff9a82a-c12b-41d6-937b-ae43cbc7710f.png)

**Comment by saddamjit** [comment]
@lalalune query - I need to have asses to VRM textures that i will use while updating and adding the skin tone color

**Comment by lalalune** [comment]
This shouldn't be related to VRM or textures, this should just be a skin color multiplier with preset swatches instead of the slider

**Comment by saddamjit** [comment]
This is done
