### ISSUE TITLE
Fix broken style

### ISSUE THREAD

**Issue by lalalune** [AtlasFoundation/AvatarCreator#50]
We have removed .scss / .css to simplify the codebase and make a React-only component. However, a few things got broken and don't look great, and need to be fixed.

**Comment by DavinciDreams** [comment]
Swap out male and female avatar bodies for cooler ones

**Comment by DavinciDreams** [comment]
update some of the icons using the figma shared

**Comment by DavinciDreams** [comment]
add login and ssave avatar features

**Comment by DavinciDreams** [comment]
download avatar

mint avatar etc.

**Comment by DavinciDreams** [comment]
Models wshould be posed or looping, not tpose

**Comment by DavinciDreams** [comment]
make the part of model being edited the focal point

**Comment by DavinciDreams** [comment]
add option to try avatrify

**Comment by DavinciDreams** [comment]
alllow users to record video of avatar actions

**Comment by DavinciDreams** [comment]
enable avatar tts and add microphone and volume ui

**Comment by DavinciDreams** [comment]
allow user to save image of avatar

**Comment by DavinciDreams** [comment]
if you have ever used ready player me, we want that basically

**Comment by DavinciDreams** [comment]
add the cool lip sync to voice stuff

**Comment by DavinciDreams** [comment]
There should also be lore

**Comment by boyykratos** [comment]
@lalalune @DavinciDreams assign it to @Emmyn5600

**Comment by Emmyn5600** [comment]
@DavinciDreams about this task `Swap out male and female avatar bodies for cooler ones` which male or female avatar should I use? because I can't see that in the Figma provided.

- The avatars are stored somewhere, so how can I access those avatars?

**Comment by Emmyn5600** [comment]
`update some of the icons using the Figma shared` not sure if there is another Figma for the page I am currently fixing the style because I can't see the icons that correspond with the one I see on the page.

![image](https://user-images.githubusercontent.com/55635977/174282343-4ba6d388-ba87-4f07-97dc-835206bcd7bf.png)

**Comment by Emmyn5600** [comment]
`add login and save avatar features`  I would need some clarification, like when the login page or feature should occur.

**Comment by Emmyn5600** [comment]
About `download avatar` or `mint avatar`. Is it the same as the below one?

![image](https://user-images.githubusercontent.com/55635977/174284441-9e86dfd7-6898-47f7-9e86-f12ecda1247a.png)

**Comment by Emmyn5600** [comment]
`Models should be posed or looping, not tpose`. So you need a model to be posed not tpose

tpose

![image](https://user-images.githubusercontent.com/55635977/174284989-b4d0ad21-ff89-4298-9cff-ba6c965636f3.png)

posed 
![Uploading image.png…]()

**Comment by Emmyn5600** [comment]
Does `add option to try avatrify` issue has to be implemented as the below video? If yes, where this feature should be applied?

https://www.youtube.com/watch?v=HbK_JOeQZK8

https://howtodiscuss.com/t/avatarify/135103

**Comment by Emmyn5600** [comment]
`alllow users to record video of avatar actions`

Do I have to add or implement the button to record a video of the avatar actions?

**Comment by Emmyn5600** [comment]
`enable avatar tts and add microphone and volume ui`.

 - You meant to add or implement the Text-to-Speech, microphone and volume ui so that a user can adjuct the volume accordingly. Do we have a figma that should direct us on where those feature should be placed or implemented?

**Comment by Emmyn5600** [comment]
`allow user to save image of avatar`

Does a user has to save image of avatar after login successfully or he/she might have access to save image even he/she is not authenticated?

**Comment by Emmyn5600** [comment]
`if you have ever used ready player me, we want that basically`

You meant to implement the similar UI for the ready player me or the same functionalities? like add eye color, skin tone or features and etc..

![image](https://user-images.githubusercontent.com/55635977/174299573-6cb91571-7ca3-4d41-9bde-4855765ea407.png)

**Comment by Emmyn5600** [comment]
`add the cool lip sync to voice stuff`

I think this would look or implemented as this one however it has to snyc to voice stuff.

![image](https://user-images.githubusercontent.com/55635977/174299973-76f202e1-e505-425a-83f6-16d445580dd0.png)

**Comment by saddamjit** [comment]
More queries by @Emmyn5600 - 
1. Which design or figma should I use or refer to while fixing the broken style in order to meet with the requirement?
 2. As explained in the issue, things have broken after removing the .scss/ .css file to simplify the codebase so can I see the old repo or demo for the project so that I can check the design or how it was working before while fixing the issue?
 
 @lalalune @DavinciDreams

**Comment by DavinciDreams** [comment]
Yes :D Nailed it.
